apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: ecommerce
    service: k6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: k6
  template:
    metadata:
      labels:
        app: ecommerce
        service: k6
    spec:
      containers:
      - name: k6
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 128Mi
        envFrom:
        - secretRef:
           name: microbs-secrets
        env:
        - name: SERVICE_NAME
          value: k6
        - name: NUM_VIRTUAL_USERS
          value: "{{ .Values.k6.virtual_user_count }}"
        - name: K6_PROMETHEUS_REMOTE_URL
          value: "{{ .Values.prometheus.url }}"
        - name: K6_PROMETHEUS_USER
          value: "{{ .Values.prometheus.username }}"
        - name: K6_PROMETHEUS_PASSWORD
          value: "{{ .Values.prometheus.apikey }}"