# Simplified config for local development

server:
  log_level: debug
  http_listen_port: 12345

#####  Metrics  ################################################################
metrics:
  wal_directory: /etc/agent/wal
  global:
    scrape_interval: 10s
    external_labels:
      cluster: microbs
  configs:
  - name: integrations
    remote_write:
    - url: ${PROMETHEUS_URL}
      basic_auth:
        username: ${PROMETHEUS_USERNAME}
        password: ${PROMETHEUS_API_KEY}
    scrape_configs:

#####  Traces  #################################################################
traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
    remote_write:
    - endpoint: ${TEMPO_URL}
      basic_auth:
        username: ${TEMPO_USERNAME}
        password: ${TEMPO_API_KEY}
    # load_balancing:
    #   exporter:
    #     insecure: true
    #   resolver:
    #     dns:
    #       hostname: grafana-agent-traces-metrics-headless.default.svc.cluster.local
    #       port: 4318
    spanmetrics:
      metrics_instance: integrations
      latency_histogram_buckets: [
        2ms, 4ms, 6ms, 8ms, 10ms, 50ms, 100ms, 150ms, 200ms, 250ms, 500ms,
        750ms, 1000ms, 1500ms, 2000ms, 2500ms, 5000ms, 10000ms, 60000ms
      ]
      dimensions:
      - name: event.outcome
      - name: k8s.pod.ip
      - name: k8s.pod.name
      - name: process.pid
      - name: service.version
    # service_graphs:
    #   enabled: true
    # scrape_configs:
    # - pipeline_stages:
    #   - cri:
    #   job_name: kubernetes-pods-name
    #   kubernetes_sd_configs:
    #   - role: pod
    #   relabel_configs:
    #   - action: replace
    #     source_labels:
    #     - __meta_kubernetes_pod_label_app
    #     target_label: __service__
    #   - action: replace
    #     source_labels:
    #     - __meta_kubernetes_pod_node_name
    #     target_label: __host__

# integrations:
#   prometheus_remote_write:
#   - url: ${PROMETHEUS_URL}
#     basic_auth:
#       username: ${PROMETHEUS_USERNAME}
#       password: ${PROMETHEUS_API_KEY}
#   postgres_exporter:
#     enabled: true
#     data_source_names:
#       - "postgresql://user1:password@product-data:5432/postgres?sslmode=disable" 
#   redis_exporter:
#     enabled: true
#     redis_addr: "session-data-replica.default.svc.cluster.local:6379"
#     relabel_configs:
#     - source_labels: [__address__]
#       target_label: instance
#       replacement: session-data
