apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: mltdemo
  labels:
    app: ecommerce
    service: payment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels:
        app: ecommerce
        service: payment
    spec:
      containers:
      - name: payment
        image: us.gcr.io/field-engineering-grafana/akc-payment-failure:3.4.17
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: SERVICE_VERSION
          value: 3.4.11-payment-failure
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python
        - name: K8S_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.app=$(K8S_APP),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME)
        envFrom:
        - secretRef:
           name: microbs-secrets
---