---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: mltdemo
  labels:
    app: ecommerce
    service: cart
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        app: ecommerce
        service: cart
    spec:
      containers:
      - name: cart
        image: us.gcr.io/field-engineering-grafana/akc-cart:3.4.28
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        envFrom:
        - secretRef:
            name: microbs-secrets
        env:
        - name: SLOW_DOWN_CART
          value: "true"
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: K8S_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.app=$(K8S_APP),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME)
        - name: FEATURE_FLAG_CART_NEW_USER_FLOW
          value: "false"