apiVersion: v1
kind: Secret
metadata:
  name: microbs-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OTLP_RECEIVER_HOST: "{{.Values.otel.host }}"
  OTLP_RECEIVER_PORT: "{{.Values.otel.port}}"
  SERVICE_VERSION: "{{.Values.service.version}}"
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.service.environment}}"