apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-k8s
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-logs
  namespace: {{ .Values.namespace }}


