apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana-agent-traces-metrics
    name: otel-collector
spec:
  ports:
  - port: {{ .Values.otel.port }}
    targetPort: {{ .Values.otel.port }}
    name: grpc
  selector:
    app: grafana-agent-traces-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent-traces-metrics-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana-agent-traces-metrics
    name: grafana-agent-traces-metrics-headless
spec:
  clusterIP: None
  ports:
  - port: 4318
    targetPort: 4318
    name: grpc
  selector:
    app: grafana-agent-traces-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-k8s
  name: grafana-agent-k8s
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: grafana-agent-k8s-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: grafana-agent-k8s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-faro
  name: grafana-agent-faro
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: grafana-agent-faro
    port: 12121
    targetPort: 12121
  selector:
    name: grafana-agent-faro

