{
 "title": "Business",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "country", "label": "Country", "query": "US,GB,GR,GL,BE,NL,DE" },
   { "name": "platform", "label": "Platform", "query": "web,mobile" }
  ]
 },
 "panels": [
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"product\"} | logfmt | session_id != `` | endpoint=`/documents` | __error__=`` | method=`POST` | endpoint=`/documents` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) ",
     "legendFormat": "BrowseProductSessions"
    },
    {
     "expr": "count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"cart\"} | logfmt | session_id != `` | method=`PUT` | endpoint=`/<product_id>/<quantity>` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n",
     "legendFormat": "AddItemsSessions"
    },
    {
     "expr": "count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"cart\"} | logfmt | session_id != `` | method=`PUT` | endpoint=`/<product_id>/<quantity>` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n/ \ncount (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"product\"} | logfmt | session_id != `` | endpoint=`/documents` | __error__=`` | method=`POST` | endpoint=`/documents` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n",
     "legendFormat": "ConversionFromProductToCart"
    },
    {
     "expr": "count (sum by(session_id) (count_over_time({app=\"ecommerce\"} | logfmt | session_id != `` | __error__=``  | endpoint!=`/healthz`| path !~`/api/v1/content/.*` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) ",
     "legendFormat": "TotalSessions"
    },
    {
     "expr": "count (sum by(session_id) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country` | device_platform =~`$platform` [$__range])))\n",
     "legendFormat": "CheckoutSessions"
    },
    {
     "expr": "count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country` | device_platform =~`$platform` | msg=`POST /process` [$__range])))",
     "legendFormat": "PaymentSessions"
    },
    {
     "expr": "count (sum by(session_id) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country` | device_platform =~`$platform` [$__range])))\n/\ncount (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"cart\"} | logfmt | session_id != `` | method=`PUT` | endpoint=`/<product_id>/<quantity>` | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n\n",
     "legendFormat": "CartToCheckoutConversion"
    },
    {
     "expr": "count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country` | device_platform =~`$platform` | msg=`POST /process` [$__range]))) \n/\ncount (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n\n\n\n",
     "legendFormat": "CheckoutToPayConversion"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment successful` | line_format `{{.msg}}` | pattern `payment successful <amount>` | unwrap amount | __error__=\"\" device_country =~`$country` | device_platform =~`$platform` [$__range]))\n"
    }
   ]
  },
  {
   "title": "Revenue Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (device_platform) (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment successful` | line_format `{{.msg}}` | pattern `payment successful <amount>` | unwrap amount | __error__=\"\" device_country =~`$country` | device_platform =~`$platform` [$__range]))\n",
     "legendFormat": "{{device_platform}}"
    },
    {
     "expr": "sum (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment successful` | line_format `{{.msg}}` | pattern `payment successful <amount>` | unwrap amount | __error__=\"\" device_country =~`$country` | device_platform =~`$platform` [$__range]))\n",
     "legendFormat": "Total Revenue"
    }
   ]
  },
  {
   "title": "Revenue Lost From Payment Error",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment timedout` | line_format `{{.msg}}` | pattern `payment timedout <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range]))  or vector(0)\n",
     "legendFormat": "{{device_country}}"
    },
    {
     "expr": "sum  (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment failed` | line_format `{{.msg}}` | pattern `payment failed <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range])) or vector(0)\n",
     "legendFormat": "{{device_country}}"
    }
   ]
  },
  {
   "title": "Revenue Lost From Payment Error By Country",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (device_country) (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment timedout` | line_format `{{.msg}}` | pattern `payment timedout <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range]))  or vector(0)\n",
     "legendFormat": "{{device_country}}"
    },
    {
     "expr": "sum by (device_country) (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment failed` | line_format `{{.msg}}` | pattern `payment failed <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range])) or vector(0)\n",
     "legendFormat": "{{device_country}}"
    }
   ]
  },
  {
   "title": "Revenue Lost From Payment Error By Device Platform",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (device_platform) (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment timedout` | line_format `{{.msg}}` | pattern `payment timedout <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range]))  or vector(0)\n",
     "legendFormat": "{{device_platform}}"
    },
    {
     "expr": "sum by (device_platform) (sum_over_time({service=\"checkout\"} | logfmt | endpoint = `/process` |= `payment failed` | line_format `{{.msg}}` | pattern `payment failed <amount>` | unwrap amount | __error__=\"\"  | device_country =~`$country` | device_platform =~`$platform` [$__range])) or vector(0)\n",
     "legendFormat": "{{device_platform}}"
    }
   ]
  },
  {
   "title": "Purchase Abandonment %",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- \n\n(\n\n  count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country` | device_platform =~`$platform` | msg=`POST /process`  [$__range]))) \n\n/\n  count (sum by(session_id, service) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country` | device_platform =~`$platform` [$__range]))) \n\n)\n\n\n"
    }
   ]
  },
  {
   "title": "Purchase Abandonment % By Country",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- \n(\n   (sum by( device_country) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country`| device_platform =~`$platform` | msg=`POST /process`  [$__range]))) \n\n/\n  (sum by( device_country) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n)",
     "legendFormat": "{{device_country}}"
    },
    {
     "expr": "1- \n(\n   (sum(count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n/\n   (sum (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Purchase Abandonment % By Device Platform",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- \n(\n   (sum by( device_platform) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country`| device_platform =~`$platform` | msg=`POST /process`  [$__range]))) \n\n/\n  (sum by( device_platform) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n)",
     "legendFormat": "{{device_platform}}"
    },
    {
     "expr": "1- \n(\n  count  (sum by(session_id, device_platform) (count_over_time({app=\"ecommerce\", service=\"payment\"} | logfmt | session_id != `` | endpoint=`/process` | method=`POST` | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n/\n  count  (sum by(session_id, device_platform) (count_over_time({app=\"ecommerce\", service=\"checkout\"} | logfmt | endpoint=`/initiate` | session_id =~ \".+\" | device_country =~`$country`| device_platform =~`$platform` [$__range]))) \n\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Sessions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "count by (device_platform) (sum by(session_id, device_platform) (count_over_time({app=\"ecommerce\"} | logfmt | session_id != `` | __error__=``  | endpoint!=`/healthz`| path !~`/api/v1/content/.*` | device_country =~`$country` | device_platform =~`$platform` [$__range])))",
     "legendFormat": "{{device_platform}}"
    },
    {
     "expr": "count  (sum by(session_id) (count_over_time({app=\"ecommerce\"} | logfmt | session_id != `` | __error__=``  | endpoint!=`/healthz`| path !~`/api/v1/content/.*` | device_country =~`$country` | device_platform =~`$platform` [$__range])))",
     "legendFormat": "Total Sessions"
    }
   ]
  },
  {
   "title": "Actions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (device_platform) (count_over_time({app=\"ecommerce\", service=\"api-gateway\"} | logfmt | endpoint!=`/healthz` | path !~`/api/v1/content/.*` | __error__=`` | device_country =~`$country` | device_platform =~`$platform` [$__range]))",
     "legendFormat": "{{device_platform}}"
    },
    {
     "expr": "sum (count_over_time({app=\"ecommerce\", service=\"api-gateway\"} | logfmt | endpoint!=`/healthz` | path !~`/api/v1/content/.*` | __error__=`` | device_country =~`$country` | device_platform =~`$platform` [$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Trace View",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "limit": 20,
     "query": "{.service.name=\"ecommerce-frontend\" && .session_id =~ \".+\" && .http.method =~ \".+\"  } "
    }
   ]
  },
  {
   "title": "Current Sessions By Country",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "count by(device_country) (sum by(session_id, device_country) (count_over_time({app=\"ecommerce\"} | logfmt | session_id != `` | __error__=``  | endpoint!=`/healthz`| path !~`/api/v1/content/.*` | device_country =~`$country` | device_platform =~`$platform` [$__range])))"
    }
   ]
  },
  {
   "title": "Current Sessions By Country",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "count by(device_country) (sum by(session_id, device_country) (count_over_time({app=\"ecommerce\"} | logfmt | session_id != `` | __error__=``  | endpoint!=`/healthz`| path !~`/api/v1/content/.*` | device_country =~`$country` | device_platform =~`$platform` [$__range])))"
    }
   ]
  }
 ]
}