{
 "title": "Front End",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "Time to First Byte",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app)",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (app)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"cls\" | logfmt | unwrap cls [$__range]) by (app)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [$__range]) by (app)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" ttfb=\" | logfmt | unwrap ttfb [5m]) by (app)",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [5m]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [5m]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" cls=\" | logfmt | unwrap cls [5m]) by (app)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [5m]) by (app)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"web-gateway\"} |~ `status=4.+` [$__range])) by (app)"
    }
   ]
  },
  {
   "title": "Exceptions for last 1h by country",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"web-gateway\"} |~ `status=4.+` | logfmt [$__range])) by (device_country)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({service=\"web-gateway\"} |~ `status=4.+` | logfmt [$__range])) by (endpoint))"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({kind=\"exception\", app=\"$app\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({app=\"$app\",kind=\"measurement\"} |= \" ttfb=\" | logfmt [$__range])) by (browser_name, browser_version))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "count_over_time({app=\"$app\",kind=\"measurement\"} |= \" ttfb=\" [$__interval])",
     "legendFormat": "visits"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "limit": 20,
     "query": "{.service.name=\"ecommerce-frontend\" && .session_id =~ \".+\" && .http.method =~ \".+\"  } "
    }
   ]
  }
 ]
}