{
 "title": "k6 Load Testing Results",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "k6_vus{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k6_http_req_failed) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_http_req_sending_avg{}", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "http_req_duration",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(k6_http_req_duration_max{})",
     "legendFormat": "Max"
    },
    {
     "expr": "max(k6_http_req_duration_p95{})",
     "legendFormat": "95th"
    },
    {
     "expr": "max(k6_http_req_duration_med{})",
     "legendFormat": "50th "
    },
    { "expr": "min(k6_http_req_blocked_min{})", "legendFormat": "Min" }
   ]
  },
  {
   "title": "http_req_duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "k6_http_req_duration_avg{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_req_connecting (95%ile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "k6_http_req_connecting_p95{} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "http_req_blocked (95%ile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "k6_http_req_blocked_p95{} > 0", "legendFormat": "{{name}}" }
   ]
  }
 ]
}