{
 "title": "Redis Dashboard",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "# Connected Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{container=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commands per second",
   "type": "graph",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_commands_total{instance=~\"$instance\"} [$__rate_interval])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "graph",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[$__rate_interval])) by (cmd)\n  /\navg(irate(redis_commands_total{instance=~\"$instance\"}[$__rate_interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "graph",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{instance=~\"$instance\"}[$__rate_interval]) / (irate(redis_keyspace_misses_total{instance=~\"$instance\"}[$__rate_interval]) + irate(redis_keyspace_hits_total{instance=~\"$instance\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{instance=~\"$instance\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Basic activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"})",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=~\"$instance\"})",
     "legendFormat": "Expiring"
    }
   ]
  },
  {
   "title": "Connected slaves by instance",
   "type": "graph",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "graph",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}