{
 "title": "Service Detail",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\"}, workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"ecommerce-$workload\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$workload\"}[1m])) by (le)) * 1",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=~\"$workload\"}[1m])) ",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  { "title": "Workload Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{cluster=\"microbs\",container=~\"$workload\"} | logfmt != \"healthz\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{cluster=\"microbs\",container=~\"$workload\"} |~ \"critical|Critical|CRITICAL|error|Error|ERROR|exception|Exception|EXCEPTION|fail|Fail|FAIL|fatal|Fatal|FATAL\""
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"integrations/kubernetes/kube-state-metrics\", container=\"$workload\"}[$__rate_interval]))",
     "legendFormat": "Restart Count"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"microbs\", namespace=\"default\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"microbs\", namespace=\"default\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"microbs\", namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"microbs\", namespace=\"default\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"microbs\", namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"microbs\", namespace=\"default\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"microbs\", namespace=\"default\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"microbs\", namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"microbs\", namespace=\"default\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"microbs\", namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=\"$workload\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(container_network_receive_bytes_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(container_network_transmit_bytes_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"integrations/kubernetes/cadvisor\", cluster=\"microbs\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"microbs\", namespace=\"default\", workload=~\"$workload\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}