{
 "title": "Services Overview",
 "tags": [
  "microbs",
  "ecommerce"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">Downtime</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">Payment Failures</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">Mean Time to Acknowledge</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">Mean Time to Repair</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">API Gateway</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">Web Gateway</h1>"
   }
  },
  {
   "title": "Monthly Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(5)" }
   ]
  },
  {
   "title": "Remaining Budget",
   "type": "stat",
   "description": "* 168 = the SLO (2 minutes 48 seconds) in seconds\n*  (sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) == How many failed probes where there in the last 30 days\n* / 7 == there are 7 services so normalise it back down to a service perspective\n* 10 == the synthetic monitoring checks run every 10 seconds so this takes the above everything which is how many windows failed and converts that to seconds\n",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "300 - (sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) / 7 * 10) or vector(300)"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "stat",
   "description": "* 168 = the SLO (2 minutes 48 seconds) in seconds\n*  (sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) == How many failed probes where there in the last 30 days\n* / 7 == there are 7 services so normalise it back down to a service perspective\n* 10 == the synthetic monitoring checks run every 10 seconds so this takes the above everything which is how many windows failed and converts that to seconds\n",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) / 7 * 10) / 300 or vector(1)"
    }
   ]
  },
  {
   "title": "Monthly Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(500)" }
   ]
  },
  {
   "title": "Monthly Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "500 - sum(count_over_time({service=\"payment\"} | logfmt | endpoint = `/process` | status != `200` [30d])) or vector(500)",
     "legendFormat": "RemainingErrors"
    }
   ]
  },
  {
   "title": "Monthly Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(25)" }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "displayValue": "true",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" },
      { "aggregates": [ "count" ], "name": "number" },
      { "aggregates": [ "count" ], "name": "opened_at" },
      {
       "aggregates": [ "count" ],
       "name": "x_977123_grafana_0_ack_datetime"
      }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "Active",
        "element": "active",
        "internal_type": { "link": "", "value": "boolean" },
        "label": "Active",
        "name": "active",
        "sys_name": "Active",
        "table": "",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {
       "conjunction": "and",
       "field": "state",
       "fieldDesc": {
        "Choices": [
         {
          "image": "",
          "label": "New",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "New",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "1"
         },
         {
          "image": "",
          "label": "In Progress",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "In Progress",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "2"
         },
         {
          "image": "",
          "label": "On Hold",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "On Hold",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "3"
         },
         {
          "image": "",
          "label": "Resolved",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Resolved",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "6"
         },
         {
          "image": "",
          "label": "Closed",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Closed",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "7"
         },
         {
          "image": "",
          "label": "Canceled",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Canceled",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "8"
         }
        ],
        "choice": "true",
        "choice_field": "",
        "choice_table": "",
        "description": "State",
        "element": "state",
        "internal_type": { "link": "", "value": "integer" },
        "label": "State",
        "name": "state",
        "sys_name": "State",
        "table": "",
        "value": "state"
       },
       "op": "=",
       "type": "integer",
       "value": "2"
      },
      {}
     ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Monthly Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(25)" }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "displayValue": "true",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" },
      { "aggregates": [ "count" ], "name": "number" },
      { "aggregates": [ "count" ], "name": "opened_at" },
      { "aggregates": [ "count" ], "name": "resolved_at" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "Active",
        "element": "active",
        "internal_type": { "link": "", "value": "boolean" },
        "label": "Active",
        "name": "active",
        "sys_name": "Active",
        "table": "",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {
       "conjunction": "and",
       "field": "state",
       "fieldDesc": {
        "Choices": [
         {
          "image": "",
          "label": "New",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "New",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "1"
         },
         {
          "image": "",
          "label": "In Progress",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "In Progress",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "2"
         },
         {
          "image": "",
          "label": "On Hold",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "On Hold",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "3"
         },
         {
          "image": "",
          "label": "Resolved",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Resolved",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "6"
         },
         {
          "image": "",
          "label": "Closed",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Closed",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "7"
         },
         {
          "image": "",
          "label": "Canceled",
          "missing": false,
          "parameters": { "name": "incident" },
          "rawLabel": "Canceled",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "8"
         }
        ],
        "choice": "true",
        "choice_field": "",
        "choice_table": "",
        "description": "State",
        "element": "state",
        "internal_type": { "link": "", "value": "integer" },
        "label": "State",
        "name": "state",
        "sys_name": "State",
        "table": "",
        "value": "state"
       },
       "op": "=",
       "type": "integer",
       "value": "6"
      },
      {}
     ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The fraction of time the target was up during the whole period.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    ceil(\n      sum by (instance, job) (increase(probe_all_success_sum{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n      /\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n    )\n  )[$__range:]\n)\n/\ncount_over_time(\n  (\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n  )[$__range:]\n)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The fraction of time the target was up during the whole period.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    ceil(\n      sum by (instance, job) (increase(probe_all_success_sum{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n      /\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n    )\n  )[$__range:]\n)\n/\ncount_over_time(\n  (\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n  )[$__range:]\n)"
    }
   ]
  },
  { "title": "Ecosystem State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Application Architecture",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(probe_success{job=\"ecommerce-web-gateway\"})",
     "legendFormat": "WebGateway"
    },
    {
     "expr": "(probe_success{job=\"ecommerce-api-gateway\"})",
     "legendFormat": "APIGateway"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"product\"}[1m])) by (le)) * 1) > bool 2000 or (probe_success{job=\"ecommerce-product\"}) == bool 0 or {name=\"ProductDBErrors\"} > bool 0",
     "legendFormat": "ProductSLI"
    },
    {
     "expr": "ProductDBErrors{name=\"ProductDBErrors\"}",
     "legendFormat": "ProductDB"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"cart\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-cart\"}) == bool 0",
     "legendFormat": "Cart"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"checkout\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-checkout\"}) == bool 0",
     "legendFormat": "Checkout"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"content\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-content\"}) == bool 0",
     "legendFormat": "Content"
    },
    {
     "expr": " (histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"payment\"}[1m])) by (le)) * 1) > bool 2000  or (probe_success{job=\"ecommerce-payment\"}) == bool 0 or sum_over_time(PaymentProcessErrors1m[1m]) > bool 0",
     "legendFormat": "Payment"
    },
    { "expr": "SessionDBErrors{}", "legendFormat": "SessionDb" },
    { "expr": "CartDBErrors{}", "legendFormat": "CartDb" }
   ]
  },
  {
   "title": "Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{}[1m])) by (service_name)",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "sum(sum(rate(traces_spanmetrics_calls_total{}[1m])) by (service_name))",
     "legendFormat": "(total)"
    }
   ]
  },
  {
   "title": "Service Error Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{event_outcome=\"failure\"}[1m])) by (service_name)\n/\nsum(rate(traces_spanmetrics_calls_total[1m])) by (service_name)",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{}[1m])) by(le, service_name)) * 1",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{}[1m])) by (le)) * 1",
     "legendFormat": "(average)"
    }
   ]
  },
  { "title": "Ecosystem Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Open Incidents by Urgency",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "true",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" },
      { "aggregates": [ "count" ], "name": "priority" },
      { "aggregates": [ "count" ], "name": "urgency" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "Active",
        "element": "active",
        "internal_type": { "link": "", "value": "boolean" },
        "label": "Active",
        "name": "active",
        "sys_name": "Active",
        "table": "",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {}
     ],
     "groupBy": [ "urgency" ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Open Incidents by Service",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      { "aggregates": [ "count" ], "name": "x_977123_grafana_0_service" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "Active",
        "element": "active",
        "internal_type": { "link": "", "value": "boolean" },
        "label": "Active",
        "name": "active",
        "sys_name": "Active",
        "table": "",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {}
     ],
     "groupBy": [ "x_977123_grafana_0_service" ],
     "limit": 25,
     "sort": [
      {}
     ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Total Open Tickets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "displayValue": "true",
     "fields": [
      { "aggregates": [ "count" ], "name": "number" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {}
     ],
     "limit": 25,
     "sort": [
      {}
     ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Overdue Incidents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "true",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "Active",
        "element": "active",
        "internal_type": { "link": "", "value": "boolean" },
        "label": "Active",
        "name": "active",
        "sys_name": "Active",
        "table": "",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {
       "conjunction": "and",
       "field": "x_977123_grafana_0_service",
       "fieldDesc": {
        "choice": "",
        "choice_field": "",
        "choice_table": "",
        "description": "X_977123_grafana_0_service",
        "element": "x_977123_grafana_0_service",
        "internal_type": { "link": "", "value": "string" },
        "label": "Service Name",
        "name": "x_977123_grafana_0_service",
        "sys_name": "Service Name",
        "table": "",
        "value": "x_977123_grafana_0_service"
       },
       "op": "ISNOTEMPTY",
       "type": "string",
       "value": ""
      },
      {
       "conjunction": "and",
       "field": "escalation",
       "fieldDesc": {
        "Choices": [
         {
          "image": "",
          "label": "Normal",
          "missing": false,
          "parameters": { "name": "task" },
          "rawLabel": "Normal",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "0"
         },
         {
          "image": "",
          "label": "Moderate",
          "missing": false,
          "parameters": { "name": "task" },
          "rawLabel": "Moderate",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "1"
         },
         {
          "image": "",
          "label": "High",
          "missing": false,
          "parameters": { "name": "task" },
          "rawLabel": "High",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "2"
         },
         {
          "image": "",
          "label": "Overdue",
          "missing": false,
          "parameters": { "name": "task" },
          "rawLabel": "Overdue",
          "reference": false,
          "selected": false,
          "used": false,
          "value": "3"
         }
        ],
        "choice": "true",
        "choice_field": "",
        "choice_table": "",
        "description": "Escalation",
        "element": "escalation",
        "internal_type": { "link": "", "value": "integer" },
        "label": "Escalation",
        "name": "escalation",
        "sys_name": "Escalation",
        "table": "",
        "value": "escalation"
       },
       "op": "=",
       "type": "integer",
       "value": "3"
      },
      {}
     ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  }
 ]
}